// ============================================================
// StadiumIQ — Google Cloud Services Integration
// Extends Google platform usage beyond Firebase/Gemini/Maps
// with Text-to-Speech, Geocoding, and Places APIs for
// enhanced venue intelligence and accessibility.
// ============================================================

// --- Google Cloud Text-to-Speech ---

/** Options for text-to-speech synthesis */
export interface TTSOptions {
  /** The text content to synthesize */
  text: string;
  /** BCP-47 language code (default: 'en-US') */
  languageCode?: string;
  /** Voice gender preference */
  gender?: 'NEUTRAL' | 'MALE' | 'FEMALE';
  /** Audio encoding format */
  encoding?: 'MP3' | 'LINEAR16' | 'OGG_OPUS';
  /** Speaking rate multiplier (0.25 to 4.0, default: 1.0) */
  speakingRate?: number;
}

/** Response from the TTS synthesis */
export interface TTSResult {
  /** Base64-encoded audio content */
  audioContent: string;
  /** Whether this was generated by the real API or fallback */
  source: 'google-cloud-tts' | 'fallback';
}

/**
 * Synthesizes speech from text using Google Cloud Text-to-Speech API.
 * This powers the accessibility feature that reads crowd alerts and
 * navigation instructions aloud for visually impaired attendees.
 *
 * Falls back to a Web Speech API placeholder when Cloud TTS is unavailable.
 *
 * @param options - Text-to-speech configuration
 * @returns Audio content result
 *
 * @example
 * ```ts
 * const audio = await synthesizeSpeech({
 *   text: 'The east wing is very crowded. Use the west entrance instead.',
 *   languageCode: 'en-US',
 * });
 * ```
 */
export async function synthesizeSpeech(options: TTSOptions): Promise<TTSResult> {
  const apiKey = process.env.GOOGLE_CLOUD_TTS_API_KEY;

  if (!apiKey || apiKey === 'your-tts-api-key') {
    return generateFallbackTTS(options.text);
  }

  try {
    const response = await fetch(
      `https://texttospeech.googleapis.com/v1/text:synthesize?key=${apiKey}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          input: { text: options.text },
          voice: {
            languageCode: options.languageCode || 'en-US',
            ssmlGender: options.gender || 'NEUTRAL',
          },
          audioConfig: {
            audioEncoding: options.encoding || 'MP3',
            speakingRate: options.speakingRate || 1.0,
          },
        }),
      }
    );

    if (!response.ok) {
      throw new Error(`TTS API returned ${response.status}`);
    }

    const data = await response.json();
    return {
      audioContent: data.audioContent,
      source: 'google-cloud-tts',
    };
  } catch (error) {
    console.warn('[StadiumIQ] Cloud TTS unavailable, using fallback:', error);
    return generateFallbackTTS(options.text);
  }
}

/**
 * Generates a fallback TTS result when the Cloud API is unavailable.
 * Returns a minimal valid response that the client can handle gracefully.
 *
 * @param text - The text that would have been synthesized
 * @returns Fallback TTS result
 */
function generateFallbackTTS(text: string): TTSResult {
  // Return a marker that tells the client to use Web Speech API instead
  const fallbackPayload = JSON.stringify({
    fallback: true,
    text: text.substring(0, 200), // Limit for safety
    engine: 'web-speech-api',
  });
  return {
    audioContent: Buffer.from(fallbackPayload).toString('base64'),
    source: 'fallback',
  };
}

// --- Google Maps Geocoding API ---

/** Geocoding result structure */
export interface GeocodingResult {
  /** Formatted full address string */
  formattedAddress: string;
  /** Structured address components */
  components: {
    street?: string;
    area?: string;
    city?: string;
    state?: string;
    country?: string;
    postalCode?: string;
  };
  /** Precise location type */
  locationType: string;
  /** Data source identifier */
  source: 'google-geocoding' | 'fallback';
}

/**
 * Performs reverse geocoding using the Google Maps Geocoding API.
 * Converts venue coordinates into structured address data for
 * richer POI descriptions and user-facing location information.
 *
 * Falls back to a pre-configured venue address when the API is unavailable.
 *
 * @param lat - Latitude coordinate
 * @param lng - Longitude coordinate
 * @returns Geocoded address result
 *
 * @example
 * ```ts
 * const address = await reverseGeocode(28.6129, 77.2295);
 * // { formattedAddress: 'Rajpath, India Gate, New Delhi, ...' }
 * ```
 */
export async function reverseGeocode(lat: number, lng: number): Promise<GeocodingResult> {
  const apiKey = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY;

  if (!apiKey || apiKey === 'your-google-maps-api-key') {
    return getFallbackGeocode(lat, lng);
  }

  try {
    const response = await fetch(
      `https://maps.googleapis.com/maps/api/geocode/json?latlng=${lat},${lng}&key=${apiKey}`
    );

    if (!response.ok) {
      throw new Error(`Geocoding API returned ${response.status}`);
    }

    const data = await response.json();

    if (data.status !== 'OK' || !data.results?.[0]) {
      return getFallbackGeocode(lat, lng);
    }

    const result = data.results[0];
    const components: GeocodingResult['components'] = {};

    for (const component of result.address_components || []) {
      if (component.types.includes('route')) components.street = component.long_name;
      if (component.types.includes('sublocality')) components.area = component.long_name;
      if (component.types.includes('locality')) components.city = component.long_name;
      if (component.types.includes('administrative_area_level_1')) components.state = component.long_name;
      if (component.types.includes('country')) components.country = component.long_name;
      if (component.types.includes('postal_code')) components.postalCode = component.long_name;
    }

    return {
      formattedAddress: result.formatted_address,
      components,
      locationType: result.geometry?.location_type || 'APPROXIMATE',
      source: 'google-geocoding',
    };
  } catch (error) {
    console.warn('[StadiumIQ] Geocoding API unavailable, using fallback:', error);
    return getFallbackGeocode(lat, lng);
  }
}

/**
 * Returns a pre-configured venue address for demo/fallback mode.
 *
 * @param lat - Latitude (used for confirmation)
 * @param lng - Longitude (used for confirmation)
 * @returns Fallback geocoding result
 */
function getFallbackGeocode(lat: number, lng: number): GeocodingResult {
  return {
    formattedAddress: `National Arena, Rajpath Marg, India Gate, New Delhi, Delhi 110001, India (${lat.toFixed(4)}, ${lng.toFixed(4)})`,
    components: {
      street: 'Rajpath Marg',
      area: 'India Gate',
      city: 'New Delhi',
      state: 'Delhi',
      country: 'India',
      postalCode: '110001',
    },
    locationType: 'APPROXIMATE',
    source: 'fallback',
  };
}

// --- Google Maps Places API ---

/** A nearby place result */
export interface NearbyPlace {
  /** Place name */
  name: string;
  /** Place category */
  type: string;
  /** Distance from venue in meters */
  distanceMeters: number;
  /** Human-readable distance */
  distanceFormatted: string;
  /** Place rating (1-5) */
  rating?: number;
  /** Whether the place is currently open */
  isOpen?: boolean;
  /** Source of the data */
  source: 'google-places' | 'fallback';
}

/**
 * Searches for nearby places around the venue using the Google Places API.
 * Used to show fans nearby transit options, hotels, restaurants, and
 * parking facilities outside the stadium.
 *
 * Falls back to curated venue-specific data when the API is unavailable.
 *
 * @param lat - Center latitude for the search
 * @param lng - Center longitude for the search
 * @param type - Google Places type filter (e.g., 'transit_station', 'parking')
 * @param radius - Search radius in meters (default: 1000)
 * @returns Array of nearby places
 *
 * @example
 * ```ts
 * const transit = await searchNearbyPlaces(28.6129, 77.2295, 'transit_station');
 * ```
 */
export async function searchNearbyPlaces(
  lat: number,
  lng: number,
  type: string,
  radius: number = 1000
): Promise<NearbyPlace[]> {
  const apiKey = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY;

  if (!apiKey || apiKey === 'your-google-maps-api-key') {
    return getFallbackPlaces(type);
  }

  try {
    const response = await fetch(
      `https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=${lat},${lng}&radius=${radius}&type=${type}&key=${apiKey}`
    );

    if (!response.ok) {
      throw new Error(`Places API returned ${response.status}`);
    }

    const data = await response.json();

    if (data.status !== 'OK' || !data.results) {
      return getFallbackPlaces(type);
    }

    return data.results.slice(0, 5).map((place: Record<string, unknown>) => {
      const placeLat = (place.geometry as Record<string, Record<string, number>>)?.location?.lat || lat;
      const placeLng = (place.geometry as Record<string, Record<string, number>>)?.location?.lng || lng;
      const distMeters = Math.round(
        haversineDistance(lat, lng, placeLat, placeLng)
      );

      return {
        name: place.name as string,
        type,
        distanceMeters: distMeters,
        distanceFormatted: distMeters < 1000 ? `${distMeters}m` : `${(distMeters / 1000).toFixed(1)}km`,
        rating: place.rating as number | undefined,
        isOpen: (place.opening_hours as Record<string, boolean>)?.open_now,
        source: 'google-places' as const,
      };
    });
  } catch (error) {
    console.warn('[StadiumIQ] Places API unavailable, using fallback:', error);
    return getFallbackPlaces(type);
  }
}

/**
 * Returns curated nearby places for demo/fallback mode.
 *
 * @param type - Place type filter
 * @returns Array of fallback nearby places
 */
function getFallbackPlaces(type: string): NearbyPlace[] {
  const fallbackData: Record<string, NearbyPlace[]> = {
    transit_station: [
      { name: 'Central Secretariat Metro', type: 'transit_station', distanceMeters: 450, distanceFormatted: '450m', rating: 4.2, isOpen: true, source: 'fallback' },
      { name: 'Udyog Bhawan Metro', type: 'transit_station', distanceMeters: 820, distanceFormatted: '820m', rating: 4.0, isOpen: true, source: 'fallback' },
      { name: 'Khan Market Metro', type: 'transit_station', distanceMeters: 1200, distanceFormatted: '1.2km', rating: 4.3, isOpen: true, source: 'fallback' },
    ],
    parking: [
      { name: 'India Gate Parking Complex', type: 'parking', distanceMeters: 200, distanceFormatted: '200m', rating: 3.8, isOpen: true, source: 'fallback' },
      { name: 'National Stadium Parking', type: 'parking', distanceMeters: 380, distanceFormatted: '380m', rating: 3.5, isOpen: true, source: 'fallback' },
    ],
    restaurant: [
      { name: 'Andhra Bhavan Canteen', type: 'restaurant', distanceMeters: 600, distanceFormatted: '600m', rating: 4.5, isOpen: true, source: 'fallback' },
      { name: 'Khan Market Food Court', type: 'restaurant', distanceMeters: 1200, distanceFormatted: '1.2km', rating: 4.1, isOpen: true, source: 'fallback' },
    ],
    hospital: [
      { name: 'RML Hospital', type: 'hospital', distanceMeters: 1500, distanceFormatted: '1.5km', rating: 3.9, isOpen: true, source: 'fallback' },
      { name: 'AIIMS Emergency', type: 'hospital', distanceMeters: 3200, distanceFormatted: '3.2km', rating: 4.4, isOpen: true, source: 'fallback' },
    ],
  };

  return fallbackData[type] || [
    { name: `Nearest ${type}`, type, distanceMeters: 500, distanceFormatted: '500m', isOpen: true, source: 'fallback' },
  ];
}

/**
 * Simple Haversine distance calculation for Places API fallback.
 *
 * @param lat1 - First point latitude
 * @param lng1 - First point longitude
 * @param lat2 - Second point latitude
 * @param lng2 - Second point longitude
 * @returns Distance in meters
 */
function haversineDistance(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 6371000;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLng = ((lng2 - lng1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) * Math.cos((lat2 * Math.PI) / 180) *
    Math.sin(dLng / 2) * Math.sin(dLng / 2);
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}
